parameters:
- name: azureSubscription
  type: string
- name: workingDirectory
  type: string
- name: scope
  type: string
- name: resourceGroupName
  type: string
- name: contactEmails
  type: string
- name: endDate
  type: string
- name: environment
  type: string
- name: maximumBudget
  type: string
- name: startDate
  type: string



stages:
- stage: ValidateDeployment
  displayName: 'Validate Deployment'
  jobs:
  - job: ValidateFiles
    steps:
    - task: AzureCLI@2
      displayName: 'Validate Bicep files'
      inputs:
        azureSubscription: ${{ parameters.azureSubscription }}
        contactEmails: ${{ parameters.contactEmails }}
        endDate: ${{ parameters.endDate }}
        environment: ${{ parameters.environment }}
        maximumBudget: ${{ parameters.maximumBudget }}
        startDate: ${{ parameters.startDate }}
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          if [ "${{ parameters.scope }}" == "subscription" ]; then
            echo "Validating Bicep files for subscription scope"
          elif [ "${{ parameters.scope }}" == "managementGroup" ]; then
            echo "Validating Bicep files for management group scope"
          elif [ "${{ parameters.scope }}" == "resourceGroup" ]; then
            echo "Validating Bicep files for resource group scope"
          else
            echo "Invalid scope value"
            exit 1
          fi
        addSpnToEnvironment: true
    - ${{ if eq(parameters['scope'], 'subscription') }}:
        - task: AzureCLI@2
          displayName: 'Validate Bicep files - Subscription'
          inputs:
            azureSubscription: ${{ parameters.azureSubscription }}
            contactEmails: ${{ parameters.contactEmails }}
            endDate: ${{ parameters.endDate }}
            environment: ${{ parameters.environment }}
            maximumBudget: ${{ parameters.maximumBudget }}
            startDate: ${{ parameters.startDate }}
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: 
               az deployment group validate --contactEmails '${{ parameters.contactEmails }}' --endDate '${{ parameters.endDate }}' --environment '${{ parameters.environment }}' --maximumBudget '${{ parameters.maximumBudget }}' --startDate '${{ parameters.startDate }}' --parameters '$(Build.SourcesDirectory)/deploybiceprg/budgets.parameters.json' --template-file '$(Build.SourcesDirectory)/deploybiceprg/budgets.bicep' --resource-group 'rgbicep'
            addSpnToEnvironment: true
    - ${{ if eq(parameters['scope'], 'resourceGroup') }}:
        - task: AzureCLI@2
          displayName: 'Validate Bicep files - Management Group'
          inputs:
            azureSubscription: ${{ parameters.azureSubscription }}
            contactEmails: ${{ parameters.contactEmails }}
            endDate: ${{ parameters.endDate }}
            environment: ${{ parameters.environment }}
            maximumBudget: ${{ parameters.maximumBudget }}
            startDate: ${{ parameters.startDate }}
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: 
               az deployment sub validate --location 'westus2'  --template-file '$(Build.SourcesDirectory)/deploybiceprg/budgets.bicep'
               echo ${{ parameters.contactEmails }}
            addSpnToEnvironment: true
    - ${{ if eq(parameters['scope'], 'managementGroup') }}:
        - task: AzureCLI@2
          displayName: 'Validate Bicep files - Resource Group'
          inputs:
            azureSubscription: ${{ parameters.azureSubscription }}
            contactEmails: ${{ parameters.contactEmails }}
            endDate: ${{ parameters.endDate }}
            environment: ${{ parameters.environment }}
            maximumBudget: ${{ parameters.maximumBudget }}
            startDate: ${{ parameters.startDate }}
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: 
               az deployment mg validate --location 'westus2' --management-group-id 'testmg' --template-file '$(Build.SourcesDirectory)/deploybiceprg/budgets.bicep'
            addSpnToEnvironment: true
